"""Public, auditable Markdown/HTML report generation for demo and real studies."""

from __future__ import annotations

import html
import json
from pathlib import Path
from typing import Any, Mapping

from .demo_study import DemoStudy, STRATEGIES, summarize_by_strategy


def build_project_report(project: Any) -> str:
    """Build a public report from the core ``ResearchProject`` model.

    The demo-specific report below has richer presentation fields, while this
    generic version is what the Dashboard uses for user-created studies.  It
    intentionally reads only persisted public fields and audit rules.
    """

    def enum_value(value: Any) -> Any:
        return getattr(value, "value", value)

    lines = [
        f"# {getattr(project, 'name', 'AI Scientist Study')}",
        "",
        "> This report summarizes a bounded local experiment workflow. It does not claim to discover scientific truth.",
        "",
        "## Research Question",
        "",
        str(getattr(project, "research_question", "")),
        "",
        "## Background and Scope",
        "",
        "Generated by the RuleBasedScientist from the user question and explicit constraints.",
        "",
        f"- Scope: {getattr(project, 'scope', '') or 'not specified'}",
        f"- Constraints: {'; '.join(getattr(project, 'constraints', []) or []) or 'none recorded'}",
        f"- Resources: {'; '.join(getattr(project, 'available_resources', []) or []) or 'local synthetic provider'}",
        "",
        "## Hypotheses",
        "",
        "| ID | Statement | Status | Confidence | Evidence |",
        "|---|---|---|---:|---|",
    ]
    hypotheses = list(getattr(project, "hypotheses", []) or [])
    for hypothesis in hypotheses:
        lines.append(
            f"| `{getattr(hypothesis, 'id', '')}` | {getattr(hypothesis, 'statement', '')} | "
            f"{enum_value(getattr(hypothesis, 'status', 'Untested'))} | "
            f"{float(getattr(hypothesis, 'confidence', 0.0)):.3f} | "
            f"{', '.join(getattr(hypothesis, 'evidence', []) or []) or '—'} |"
        )
    lines += [
        "",
        "## Methods and Experiments",
        "",
        "| Experiment | Hypothesis | Provider design | Seed | Status | Runs |",
        "|---|---|---|---:|---|---:|",
    ]
    experiments = list(getattr(project, "experiments", []) or [])
    for experiment in experiments:
        design = getattr(experiment, "design", None)
        lines.append(
            f"| `{getattr(experiment, 'id', '')}` | `{getattr(design, 'hypothesis_id', '')}` | "
            f"{getattr(design, 'name', '')} | {getattr(design, 'seed', '')} | "
            f"{enum_value(getattr(experiment, 'status', 'Queued'))} | {len(getattr(experiment, 'runs', []) or [])} |"
        )
    lines += ["", "## Results", "", "| Experiment | n | Mean | Median | Std | 95% CI | Effect size | Success rate |", "|---|---:|---:|---:|---:|---|---:|---:|"]
    for experiment in experiments:
        analysis = getattr(experiment, "analysis", None)
        if analysis is None:
            continue
        ci = getattr(analysis, "confidence_interval", None) or (0.0, 0.0)
        fmt = lambda value: "—" if value is None else f"{float(value):.3f}"
        lines.append(
            f"| `{getattr(experiment, 'id', '')}` | {getattr(analysis, 'sample_count', 0)} | {fmt(getattr(analysis, 'mean', None))} | "
            f"{fmt(getattr(analysis, 'median', None))} | {fmt(getattr(analysis, 'std', None))} | "
            f"[{fmt(ci[0])}, {fmt(ci[1])}] | {fmt(getattr(analysis, 'effect_size', None))} | {fmt(getattr(analysis, 'success_rate', None))} |"
        )
    best = max(hypotheses, key=lambda item: float(getattr(item, "confidence", 0.0)), default=None)
    lines += [
        "",
        "## Interpretation",
        "",
        f"Current highest-confidence hypothesis: `{getattr(best, 'id', 'none')}` — {getattr(best, 'status', 'no evidence') if best else 'no evidence'}.",
        "This is a rule-scoped interpretation of the recorded synthetic/local evidence.",
        "",
        "## Rejected and Inconclusive Hypotheses",
        "",
    ]
    for hypothesis in hypotheses:
        status = enum_value(getattr(hypothesis, "status", "Untested"))
        if status != "Supported":
            lines.append(f"- `{getattr(hypothesis, 'id', '')}` — {status}; no conclusion beyond the recorded evidence.")
    lines += [
        "",
        "## Limitations",
        "",
        "- Synthetic/Mock observations are not evidence about a real-world population.",
        "- Confidence is a transparent heuristic, not a calibrated probability.",
        "- Failed infrastructure or invalid-design runs do not reject a hypothesis.",
        "",
        "## Next Work",
        "",
        "1. Review the design and budget before enabling any external adapter.",
        "2. Repeat with an independently generated dataset and a preregistered criterion.",
        "3. Compare the follow-up result with the audit lineage below.",
        "",
        "## Scientific Audit Trail",
        "",
    ]
    for event in list(getattr(project, "audit_trail", []) or []):
        lines.append(
            f"- `{getattr(event, 'id', '')}` `{getattr(event, 'event_type', '')}` "
            f"subject `{getattr(event, 'subject_id', '')}`; rule: {getattr(event, 'rule', '')}"
        )
    lines += ["", "## Reproducibility", "", f"- Project ID: `{getattr(project, 'id', '')}`", f"- Status: `{enum_value(getattr(project, 'status', ''))}`", "- Default provider cost: `$0.00`", ""]
    return "\n".join(lines)


def write_project_report(project: Any, output_path: str | Path) -> Path:
    path = Path(output_path)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(build_project_report(project), encoding="utf-8")
    return path


def _fmt(value: Any, digits: int = 3) -> str:
    if isinstance(value, float):
        return f"{value:.{digits}f}"
    return str(value)


def build_report(study: DemoStudy, *, chart_paths: Mapping[str, str] | None = None) -> str:
    """Build a complete, human-readable report without private reasoning text."""
    summaries = summarize_by_strategy(study.runs)
    best = max(STRATEGIES, key=lambda strategy: (float(summaries[strategy].get("mean", 0.0)), strategy))
    best_hypothesis = next((h for h in study.hypotheses if any(c.strategy == best and c.hypothesis_id == h.id for c in study.configurations)), None)
    chart_paths = chart_paths or {}
    lines: list[str] = [
        f"# {study.name}",
        "",
        "> This is a deterministic synthetic study. It demonstrates an auditable scientific loop; it does not claim to discover scientific truth about real agents.",
        "",
        "## Research Question",
        "",
        study.research_question,
        "",
        "## Background and Scope",
        "",
        study.background,
        "",
        "- Scope: " + "; ".join(study.scope),
        "- Resources: " + "; ".join(study.available_resources),
        "- Constraints: " + "; ".join(study.constraints),
        "",
        "## Hypotheses",
        "",
        "| ID | Strategy | Status | Confidence | Evidence |",
        "|---|---|---:|---:|---|",
    ]
    for hypothesis in study.hypotheses:
        strategy = next((c.strategy for c in study.configurations if c.hypothesis_id == hypothesis.id), "")
        lines.append(f"| `{hypothesis.id}` | {strategy} | {hypothesis.status} | {_fmt(hypothesis.confidence)} | {', '.join(hypothesis.evidence) or '—'} |")
    lines += [
        "",
        "## Methods and Configurations",
        "",
        "Each configuration uses `synthetic-long-horizon-memory-v1`, a fixed seed, 24 generated samples, and the same recall-score success criterion (`score >= 0.65`).",
        "",
        "| Strategy | Seed | Independent variable | Dependent variable | Control |",
        "|---|---:|---|---|---|",
    ]
    for config in study.configurations:
        lines.append(f"| {config.strategy} | {config.seed} | `{config.independent_variable}` | `{config.dependent_variable}` | {config.control} |")
    lines += [
        "",
        "## Experiment Queue and Selection",
        "",
        f"- Completed experiments: **{len(study.experiments)}**",
        f"- Completed runs: **{len(study.runs)}**",
        f"- Selection rounds: **{max((e.round for e in study.experiments), default=0)}**",
        f"- Budget: {json.dumps(study.budget, ensure_ascii=False)}",
        "",
        "| Round | Experiment | Strategy | Runs | Selection rule | Status |",
        "|---:|---|---|---:|---|---|",
    ]
    for experiment in study.experiments:
        strategy = next((c.strategy for c in study.configurations if c.id == experiment.configuration_id), "")
        lines.append(f"| {experiment.round} | `{experiment.id}` | {strategy} | {len(experiment.run_ids)} | {experiment.selection_rule} | {experiment.status} |")
    lines += [
        "",
        "## Results",
        "",
        "| Strategy | n | Mean | Median | Std | 95% CI | Effect size vs control | Success rate |",
        "|---|---:|---:|---:|---:|---|---:|---:|",
    ]
    for strategy in STRATEGIES:
        summary = summaries[strategy]
        ci = summary.get("ci95", [0, 0])
        lines.append(f"| {strategy} | {summary['n']} | {_fmt(summary['mean'])} | {_fmt(summary['median'])} | {_fmt(summary['std'])} | [{_fmt(ci[0])}, {_fmt(ci[1])}] | {_fmt(summary['effect_size'])} | {_fmt(summary['success_rate'])} |")
    lines += [
        "",
        "## Interpretation",
        "",
        f"Within this synthetic benchmark, **{best}** has the highest observed mean score ({_fmt(summaries[best]['mean'])}). The current best hypothesis is `{best_hypothesis.id if best_hypothesis else 'n/a'}` with status **{best_hypothesis.status if best_hypothesis else 'n/a'}** and confidence {_fmt(best_hypothesis.confidence if best_hypothesis else 0.0)}.",
        "",
        "This conclusion is scoped to the generated data and explicit update rule. It should not be generalized to real agents without independent data and review.",
        "",
        "## Rejected or Inconclusive Hypotheses",
        "",
    ]
    for hypothesis in study.hypotheses:
        if hypothesis.status != "Supported":
            strategy = next((c.strategy for c in study.configurations if c.hypothesis_id == hypothesis.id), "")
            lines.append(f"- **{strategy}** — {hypothesis.status}; confidence {_fmt(hypothesis.confidence)}. Evidence IDs: {', '.join(hypothesis.evidence) or 'none'}.")
    lines += [
        "",
        "## Next Work",
        "",
        "1. Repeat with a separately generated synthetic dataset and preregistered thresholds.",
        "2. Add missing-data and infrastructure-failure scenarios to validate failure classification.",
        "3. Connect a user-approved external provider only through an adapter with the same budget controls.",
        "",
        "## Limitations",
        "",
        "- Synthetic observations are generated by transparent hand-written rules.",
        "- Confidence is a heuristic evidence score, not a calibrated probability.",
        "- The simplified effect size uses pooled standard deviation and does not replace a full statistical analysis.",
        "- No external model, web request, purchase, or publication is performed.",
        "",
        "## Scientific Audit Trail",
        "",
        "Every result points to a configuration, hypothesis, experiment, run seed, data hash, and update decision. The update rule is recorded below:",
        "",
        "`confidence = clamp(0.55 × mean_score + 0.45 × success_rate, 0.01, 0.99)`; status thresholds: Supported ≥ 0.68, Rejected ≤ 0.48, otherwise Inconclusive.",
        "",
        "### Decisions",
        "",
    ]
    for decision in study.decisions:
        lines.append(f"- `{decision.get('id', '')}` ({decision.get('type', '')}, round {decision.get('round', '')}): {decision.get('rule', 'selection decision')}")
    if chart_paths:
        lines += ["", "## Figures", ""]
        for name, path in chart_paths.items():
            lines.append(f"- `{name}`: `{path}`")
    lines += ["", "## Reproducibility", "", f"- Study ID: `{study.id}`", f"- Code version: `{study.code_version}`", f"- Created: `{study.created_at}`", f"- Completed: `{study.completed_at}`", "- Provider cost: `$0.00`"]
    return "\n".join(lines) + "\n"


def write_report(study: DemoStudy, output_path: str | Path, *, chart_paths: Mapping[str, str] | None = None) -> Path:
    path = Path(output_path)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(build_report(study, chart_paths=chart_paths), encoding="utf-8")
    return path


def write_html_report(study: DemoStudy, output_path: str | Path, *, chart_paths: Mapping[str, str] | None = None) -> Path:
    """Write a self-contained HTML wrapper around the Markdown-style report."""
    report = build_report(study, chart_paths=chart_paths)
    # Keep this dependency-free.  The Markdown remains readable in <pre> and
    # can be converted by the desktop UI if a Markdown renderer is available.
    escaped = html.escape(report)
    path = Path(output_path)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(f"<!doctype html><meta charset='utf-8'><title>{html.escape(study.name)}</title><style>body{{font-family:system-ui;max-width:1100px;margin:2rem auto;padding:0 1rem}}pre{{white-space:pre-wrap;line-height:1.45}}</style><pre>{escaped}</pre>\n", encoding="utf-8")
    return path


def generate_demo_artifacts(output_dir: str | Path, *, seed: int = 20261004) -> dict[str, str]:
    """Run the demo and write database, report, charts, and artifact manifest."""
    from .charts import write_charts, write_dashboard_snapshot
    from .demo_study import persist_demo_study, run_demo_study

    root = Path(output_dir)
    root.mkdir(parents=True, exist_ok=True)
    study = run_demo_study(seed=seed)
    persist_demo_study(study, root)
    chart_paths = write_charts(study, root / "charts")
    snapshot_path = write_dashboard_snapshot(study, root / "dashboard_snapshot.png")
    md_path = write_report(study, root / "research_report.md", chart_paths=chart_paths)
    html_path = write_html_report(study, root / "research_report.html", chart_paths=chart_paths)
    # Keep a transactional core-engine checkpoint beside the human-readable
    # DemoStudy JSON.  The report remains based on the richer presentation
    # model, while the SQLite file proves that the actual engine can close and
    # reopen a two-round study without losing audit lineage.
    core_database: Path | None = None
    try:
        from .engine import ScientistEngine
        from .models import ResearchBudget
        from .persistence import SQLiteProjectStore

        core_engine = ScientistEngine()
        core_engine.create_project(
            study.research_question,
            name=study.name,
            scope="; ".join(study.scope),
            constraints=study.constraints,
            available_resources=study.available_resources,
            metrics=("score",),
            budget=ResearchBudget(
                maximum_experiments=10,
                maximum_runs=100,
                maximum_runtime_seconds=30,
                estimated_api_cost=0.0,
            ),
        )
        core_engine.run_scientific_cycle(rounds=2, runs_per_experiment=4, seed=seed)
        core_database = root / "memory_strategy_study.sqlite3"
        SQLiteProjectStore().save(core_engine.require_project(), core_database)
    except Exception as exc:
        # The presentation demo is still valid if an optional persistence
        # backend is unavailable; make the reason visible in the manifest.
        (root / "core_checkpoint_warning.txt").write_text(str(exc) + "\n", encoding="utf-8")

    manifest = {
        "study": str(root / "memory_strategy_study.json"),
        "core_database": str(core_database) if core_database else None,
        "report": str(md_path),
        "html_report": str(html_path),
        "charts": chart_paths,
        "dashboard_snapshot": snapshot_path,
        "run_count": len(study.runs),
        "experiment_count": len(study.experiments),
    }
    (root / "demo_manifest.json").write_text(json.dumps(manifest, indent=2) + "\n", encoding="utf-8")
    result = {"database": str(root / "memory_strategy_study.json"), "report": str(md_path), "html_report": str(html_path), "dashboard_snapshot": snapshot_path, **chart_paths}
    if core_database:
        result["core_database"] = str(core_database)
    return result
