"""Offline, auditable AI Scientist Mini package."""

__version__ = "0.1.0"

# Stable convenience imports for notebooks and adapters.  The UI is optional;
# importing the package never starts a window or contacts a network.
from .core import (  # noqa: E402,F401
    ApprovalRequired,
    Budget,
    BudgetError,
    ExperimentConfig,
    ExperimentExecution,
    ExperimentProvider,
    ExperimentResult,
    ExperimentRun,
    ExperimentStatus,
    Hypothesis,
    HypothesisStatus,
    MockLLMExperimentProvider,
    Project,
    ProjectStatus,
    PythonFunctionProvider,
    ResearchStore,
    RuleBasedScientist,
    ScientificEngine,
    StopRequested,
    SyntheticProvider,
    run_memory_strategy_study,
)
from .reporting import (  # noqa: E402,F401
    ResultAnalyzer,
    ScientistJournal,
    analyze_results,
    build_demo_report,
    build_hypothesis_graph,
    build_scientist_journal,
    generate_demo_report,
    generate_report,
    render_report,
    save_hypothesis_graph,
    save_report,
)
from .visualization import (  # noqa: E402,F401
    create_charts,
    save_charts,
)
from .adapters import (  # noqa: E402,F401
    ADAPTER_PROTOCOL_VERSION,
    AdapterError,
    AdapterRequest,
    AdapterResponse,
    AgentArenaAdapter,
    BenchmarkFactoryAdapter,
    ExperimentAdapter,
    LLMLabAdapter,
    LocalJsonAdapter,
    Paper2LabAdapter,
    ReservedExternalAdapter,
)

__all__ = [
    "ApprovalRequired",
    "Budget",
    "BudgetError",
    "ExperimentConfig",
    "ExperimentExecution",
    "ExperimentProvider",
    "ExperimentResult",
    "ExperimentRun",
    "ExperimentStatus",
    "Hypothesis",
    "HypothesisStatus",
    "MockLLMExperimentProvider",
    "Project",
    "ProjectStatus",
    "PythonFunctionProvider",
    "ResearchStore",
    "RuleBasedScientist",
    "ScientificEngine",
    "StopRequested",
    "SyntheticProvider",
    "run_memory_strategy_study",
    "ResultAnalyzer",
    "ScientistJournal",
    "analyze_results",
    "build_demo_report",
    "build_hypothesis_graph",
    "build_scientist_journal",
    "generate_demo_report",
    "generate_report",
    "render_report",
    "save_hypothesis_graph",
    "save_report",
    "create_charts",
    "save_charts",
    "ADAPTER_PROTOCOL_VERSION",
    "AdapterError",
    "AdapterRequest",
    "AdapterResponse",
    "ExperimentAdapter",
    "LocalJsonAdapter",
    "ReservedExternalAdapter",
    "LLMLabAdapter",
    "AgentArenaAdapter",
    "BenchmarkFactoryAdapter",
    "Paper2LabAdapter",
]
